name: Terraform

on:
  push:
    branches:
      - "**"

jobs:
  tf-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
      - uses: hashicorp/setup-terraform@v1

      - name: configure fake creds
        id: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

      - name: setup
        working-directory: glue_scripts
        id: setup
        run: sbt assembly

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var 'aws_region=us-west-1' -var 'account_id=12345689' -var 'api_key=12345'
